In [1]:
import pandas as pd
import numpy as np

In [29]:
path_straight = 'agent\model_store\ORG\eval_stats_HDDriveDQN_V0_GRU_8f_Trueres_LEG1_STRAIGHT.csv'
path_curved = 'agent\model_store\ORG\eval_stats_HDDriveDQN_V0_GRU_8f_Trueres_LEG2_CURVED.csv'
path_junction = 'agent\model_store\ORG\eval_stats_HDDriveDQN_V0_GRU_8f_Trueres_LEG3_JUNCTION.csv'
path_all = 'agent\model_store\ORG\eval_stats_HDDriveDQN_V0_GRU_8f_Trueres_LEG4_ALL.csv'
def process(path):
    df = pd.read_csv(path)
    categories = df['category'].unique()
    metrics = ['collisionCount',	'wrongLaneCount',	'outsideDrivingLanesCount',	'offRoadCount',	'routeCompletionPer']
    d = {}
    for category in categories:
        d[category] = df[df['category'] == category][metrics].mean()
    df = pd.DataFrame(d).transpose()
    df['tot_infracs'] = df[metrics[:-1]].sum(axis=1)
    df['ds'] =  df['routeCompletionPer']/(df['tot_infracs']+1)
    return df

In [30]:
df_straight = process(path_straight)
df_curved = process(path_curved)
df_junction = process(path_junction)
df_all = process(path_all)

In [25]:
df_straight

,collisionCount,wrongLaneCount,outsideDrivingLanesCount,offRoadCount,routeCompletionPer,tot_infracs,ds
test_straight,1.100000,0.200000,0.700000,0.700000,73.160450,2.700000,19.773095
test_curved,0.150000,0.650000,0.500000,0.950000,56.752944,2.250000,17.462444
test_junction_3,0.842105,0.210526,1.052632,1.789474,41.868341,3.894737,8.553747
test_junction_4,0.433333,0.000000,1.100000,1.300000,60.212149,2.833333,15.707517
straight,0.733333,0.200000,0.200000,0.266667,63.822923,1.400000,26.592885
curved,0.714286,0.057143,0.800000,1.057143,51.849026,2.628571,14.289102
junction_3,0.620000,0.400000,0.280000,0.640000,40.074105,1.940000,13.630648
junction_4,0.200000,0.022222,0.688889,0.955556,23.971699,1.866667,8.362221

In [26]:
df_curved

,collisionCount,wrongLaneCount,outsideDrivingLanesCount,offRoadCount,routeCompletionPer,tot_infracs,ds
test_straight,0.222222,0.888889,0.555556,1.444444,82.574583,3.111111,20.085709
test_curved,0.650000,0.600000,0.400000,0.750000,84.692424,2.400000,24.909536
test_junction_3,0.578947,0.052632,1.421053,1.947368,45.046571,4.000000,9.009314
test_junction_4,0.300000,1.000000,1.833333,2.200000,44.651027,5.333333,7.050162
straight,0.266667,0.933333,0.666667,0.800000,72.340332,2.666667,19.729181
curved,0.000000,0.029412,0.323529,0.588235,69.946983,0.941176,36.033294
junction_3,0.938776,0.326531,0.653061,1.000000,54.638483,2.918367,13.944196
junction_4,0.159091,0.250000,0.886364,1.090909,45.138106,2.386364,13.329373

In [27]:
df_junction

,collisionCount,wrongLaneCount,outsideDrivingLanesCount,offRoadCount,routeCompletionPer,tot_infracs,ds
test_straight,1.400000,1.100000,0.000000,0.000000,86.070242,2.500000,24.591498
test_curved,0.100000,1.450000,0.350000,0.750000,84.888211,2.650000,23.257044
test_junction_3,0.000000,0.800000,0.300000,0.350000,64.221697,1.450000,26.212937
test_junction_4,0.300000,0.366667,0.533333,0.933333,66.617350,2.133333,21.260856
straight,0.200000,1.066667,0.000000,0.000000,65.015324,1.266667,28.683231
curved,0.200000,0.457143,0.971429,1.571429,80.121068,3.200000,19.076445
junction_3,0.160000,0.760000,0.100000,0.380000,73.064073,1.400000,30.443364
junction_4,0.076923,0.794872,0.871795,1.025641,65.346744,2.769231,17.336891

In [31]:
df_all

,collisionCount,wrongLaneCount,outsideDrivingLanesCount,offRoadCount,routeCompletionPer,tot_infracs,ds
test_straight,0.500000,0.100000,0.700000,1.400000,83.432105,2.700000,22.549217
test_curved,0.157895,0.631579,0.684211,1.157895,81.053873,2.631579,22.319182
test_junction_3,1.100000,0.000000,1.050000,1.200000,43.582727,3.350000,10.019018
test_junction_4,0.033333,0.433333,0.666667,0.900000,61.987751,2.033333,20.435522
straight,0.466667,1.600000,0.466667,0.466667,64.443070,3.000000,16.110767
curved,0.200000,0.114286,0.657143,1.114286,71.303306,2.085714,23.107553
junction_3,0.102041,0.469388,0.469388,0.693878,72.634109,1.734694,26.560234
junction_4,0.025641,0.461538,0.589744,0.743590,71.688324,1.820513,25.416769